services:
  web:
    image: php:8.1-apache
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
    depends_on:
      - database

  database:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1111:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD} 
    depends_on:
      - database

# http://localhost:1111 PhpMyAdmin
# http://localhost Web